//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Climbing.Guide.Forms.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Guide {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Guide() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Climbing.Guide.Forms.Resources.Strings.Guide", typeof(Guide).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        public static string Explore_Title {
            get {
                return ResourceManager.GetString("Explore_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide.
        /// </summary>
        public static string Guide_Title {
            get {
                return ResourceManager.GetString("Guide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access info.
        /// </summary>
        public static string Manage_Area_Access {
            get {
                return ResourceManager.GetString("Manage_Area_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descent info.
        /// </summary>
        public static string Manage_Area_Descent {
            get {
                return ResourceManager.GetString("Manage_Area_Descent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Manage_Area_Info {
            get {
                return ResourceManager.GetString("Manage_Area_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Manage_Area_Into_Title {
            get {
                return ResourceManager.GetString("Manage_Area_Into_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Manage_Area_Map_Title {
            get {
                return ResourceManager.GetString("Manage_Area_Map_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Manage_Area_Name {
            get {
                return ResourceManager.GetString("Manage_Area_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Manage_Area_Region {
            get {
                return ResourceManager.GetString("Manage_Area_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrictions.
        /// </summary>
        public static string Manage_Area_Restrictions {
            get {
                return ResourceManager.GetString("Manage_Area_Restrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Manage_Region_Info {
            get {
                return ResourceManager.GetString("Manage_Region_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Manage_Region_Into_Title {
            get {
                return ResourceManager.GetString("Manage_Region_Into_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Manage_Region_Map_Title {
            get {
                return ResourceManager.GetString("Manage_Region_Map_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Manage_Region_Name {
            get {
                return ResourceManager.GetString("Manage_Region_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrictions.
        /// </summary>
        public static string Manage_Region_Restrictions {
            get {
                return ResourceManager.GetString("Manage_Region_Restrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string Manage_Sector_Access {
            get {
                return ResourceManager.GetString("Manage_Sector_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Manage_Sector_Area {
            get {
                return ResourceManager.GetString("Manage_Sector_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descent.
        /// </summary>
        public static string Manage_Sector_Descent {
            get {
                return ResourceManager.GetString("Manage_Sector_Descent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Manage_Sector_Info {
            get {
                return ResourceManager.GetString("Manage_Sector_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Manage_Sector_Into_Title {
            get {
                return ResourceManager.GetString("Manage_Sector_Into_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Manage_Sector_Map_Title {
            get {
                return ResourceManager.GetString("Manage_Sector_Map_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Manage_Sector_Name {
            get {
                return ResourceManager.GetString("Manage_Sector_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Manage_Sector_Region {
            get {
                return ResourceManager.GetString("Manage_Sector_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrictions.
        /// </summary>
        public static string Manage_Sector_Restrictions {
            get {
                return ResourceManager.GetString("Manage_Sector_Restrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_Title {
            get {
                return ResourceManager.GetString("Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guiding.
        /// </summary>
        public static string Section_Title {
            get {
                return ResourceManager.GetString("Section_Title", resourceCulture);
            }
        }
    }
}
