//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Climbing.Guide.Forms.Resources.Strings {


   /// <summary>
   ///   A strongly-typed resource class, for looking up localized strings, etc.
   /// </summary>
   // This class was auto-generated by the StronglyTypedResourceBuilder
   // class via a tool like ResGen or Visual Studio.
   // To add or remove a member, edit your .ResX file then rerun ResGen
   // with the /str option, or rebuild your VS project.
   [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Routes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Routes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Climbing.Guide.Forms.Resources.Strings.Routes", typeof(Routes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Add_Area_Selection_Item {
            get {
                return ResourceManager.GetString("Add_Area_Selection_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick image and add a route.
        /// </summary>
        public static string Add_Route_From_Gallery_Selection_Item {
            get {
                return ResourceManager.GetString("Add_Route_From_Gallery_Selection_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a picture and add a route.
        /// </summary>
        public static string Add_Route_From_Image_Selection_Item {
            get {
                return ResourceManager.GetString("Add_Route_From_Image_Selection_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add_Title {
            get {
                return ResourceManager.GetString("Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Route_Edit_Area {
            get {
                return ResourceManager.GetString("Route_Edit_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string Route_Edit_Difficulty {
            get {
                return ResourceManager.GetString("Route_Edit_Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FA.
        /// </summary>
        public static string Route_Edit_FA {
            get {
                return ResourceManager.GetString("Route_Edit_FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about the route.
        /// </summary>
        public static string Route_Edit_Info {
            get {
                return ResourceManager.GetString("Route_Edit_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Route_Edit_Into_Title {
            get {
                return ResourceManager.GetString("Route_Edit_Into_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length in meters.
        /// </summary>
        public static string Route_Edit_Length {
            get {
                return ResourceManager.GetString("Route_Edit_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Route_Edit_Map_Title {
            get {
                return ResourceManager.GetString("Route_Edit_Map_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route name.
        /// </summary>
        public static string Route_Edit_Name {
            get {
                return ResourceManager.GetString("Route_Edit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Route_Edit_Region {
            get {
                return ResourceManager.GetString("Route_Edit_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route type.
        /// </summary>
        public static string Route_Edit_Route_Type {
            get {
                return ResourceManager.GetString("Route_Edit_Route_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpine route.
        /// </summary>
        public static string Route_Edit_Route_Type_Alpine {
            get {
                return ResourceManager.GetString("Route_Edit_Route_Type_Alpine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boulder.
        /// </summary>
        public static string Route_Edit_Route_Type_Boulder {
            get {
                return ResourceManager.GetString("Route_Edit_Route_Type_Boulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport route.
        /// </summary>
        public static string Route_Edit_Route_Type_Sport {
            get {
                return ResourceManager.GetString("Route_Edit_Route_Type_Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        public static string Route_Edit_Schema_Title {
            get {
                return ResourceManager.GetString("Route_Edit_Schema_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string Route_Edit_Sector {
            get {
                return ResourceManager.GetString("Route_Edit_Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        public static string Route_Title {
            get {
                return ResourceManager.GetString("Route_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string Route_Title_Format {
            get {
                return ResourceManager.GetString("Route_Title_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while trying to show route {0}..
        /// </summary>
        public static string Route_View_Error_Message {
            get {
                return ResourceManager.GetString("Route_View_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        public static string Schema {
            get {
                return ResourceManager.GetString("Schema", resourceCulture);
            }
        }
    }
}
